#!/system/recovery/sh

	cat /dev/input/event1 > /dev/keycheck&
	sleep 3
	kill -9 $!
	if [ -s /dev/keycheck ]
	then

	# remount rootfs rw
	mount -o remount,rw rootfs /

	# Umount MTDs
	umount -l /dev/block/mtdblock1
	umount -l /dev/block/mtdblock2
	umount -l /dev/block/mtdblock3

	# Mount recovery partition
	rm -r /sbin
	rm -f etc
	tar -xjf /system/recovery/recovery.tar.bz2

	# Umount /system
	umount -l /dev/block/mtdblock0

	chroot / /init

	fi

	/system/bin/charger
	
	
	# remount rw
	mount -o remount,rw rootfs /

	cd /
	rm -r /sdcard
	rm init*
	rm logo.rle
	rm default.prop
	tar -xf /system/bin/ramdisk.tar


	chroot / /init
